# Generated by Django 4.1.5 on 2023-01-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesWithChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=30)),
                ('chat_text', models.TextField()),
            ],
            options={
                'db_table': 'MessagesWithChatBot',
            },
        ),
    ]
