# Generated by Django 4.2.2 on 2023-10-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0002_remove_users_username_users_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
    ]
