# Generated by Django 4.2.2 on 2023-10-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0003_remove_users_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
    ]
