# Generated by Django 4.2.2 on 2023-10-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0004_remove_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.CharField(default='profile_basic.png', max_length=255),
        ),
    ]
