# Generated by Django 4.2.2 on 2023-10-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0005_alter_users_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
