# Generated by Django 4.2.2 on 2023-10-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0006_users_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status_message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
