# Generated by Django 4.2.2 on 2023-11-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0007_users_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('away', 'Away')], default='active', max_length=10),
        ),
    ]
