# Generated by Django 4.2.2 on 2023-11-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0008_users_is_online_alter_users_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
