# Generated by Django 4.2.2 on 2023-11-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0009_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('offline', 'Offline')], default='online', max_length=10),
        ),
    ]
