# Generated by Django 4.2.2 on 2023-10-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting_main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='is_chatbot',
            field=models.BooleanField(default=False),
        ),
    ]
