# Generated by Django 4.2.2 on 2023-11-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting_main_page', '0002_conversations_is_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('SYSTEM', 'system'), ('DANGER', 'danger'), ('FRIENDS', 'friends'), ('TEAM', 'team'), ('NORMAL', 'normal')], max_length=20),
        ),
    ]
