# Generated by Django 4.2.2 on 2023-11-18 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatting_main_page', '0004_remove_notifications_user_notificationrecivers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageRecivers',
            new_name='MessageReceivers',
        ),
        migrations.RenameModel(
            old_name='NotificationRecivers',
            new_name='NotificationReceivers',
        ),
    ]
