# Generated by Django 4.2.2 on 2023-11-27 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatting_main_page', '0005_rename_messagerecivers_messagereceivers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='last_chat_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
